/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as AppRouteImport } from './routes/app'
import { Route as ApiCoachRouteImport } from './routes/api/coach'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCoachRouteImport } from './routes/app.coach'
import { Route as AppGithubRouteImport } from './routes/app.github'
import { Route as AppJobMatchRouteImport } from './routes/app.job-match'
import { Route as AppPlanRouteImport } from './routes/app.plan'
import { Route as AppPortfolioRouteImport } from './routes/app.portfolio'
import { Route as AppResumeRouteImport } from './routes/app.resume'
import { Route as AppSkillGapsRouteImport } from './routes/app.skill-gaps'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppGithubRoute = AppGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => AppRoute,
} as any)
const AppJobMatchRoute = AppJobMatchRouteImport.update({
  id: '/job-match',
  path: '/job-match',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppResumeRoute = AppResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillGapsRoute = AppSkillGapsRouteImport.update({
  id: '/skill-gaps',
  path: '/skill-gaps',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/app': typeof AppRouteWithChildren
  '/api/coach': typeof ApiCoachRoute
  '/app/coach': typeof AppCoachRoute
  '/app/github': typeof AppGithubRoute
  '/app/job-match': typeof AppJobMatchRoute
  '/app/plan': typeof AppPlanRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/resume': typeof AppResumeRoute
  '/app/skill-gaps': typeof AppSkillGapsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/api/coach': typeof ApiCoachRoute
  '/app/coach': typeof AppCoachRoute
  '/app/github': typeof AppGithubRoute
  '/app/job-match': typeof AppJobMatchRoute
  '/app/plan': typeof AppPlanRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/resume': typeof AppResumeRoute
  '/app/skill-gaps': typeof AppSkillGapsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/app': typeof AppRouteWithChildren
  '/api/coach': typeof ApiCoachRoute
  '/app/coach': typeof AppCoachRoute
  '/app/github': typeof AppGithubRoute
  '/app/job-match': typeof AppJobMatchRoute
  '/app/plan': typeof AppPlanRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/resume': typeof AppResumeRoute
  '/app/skill-gaps': typeof AppSkillGapsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/app'
    | '/api/coach'
    | '/app/coach'
    | '/app/github'
    | '/app/job-match'
    | '/app/plan'
    | '/app/portfolio'
    | '/app/resume'
    | '/app/skill-gaps'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/api/coach'
    | '/app/coach'
    | '/app/github'
    | '/app/job-match'
    | '/app/plan'
    | '/app/portfolio'
    | '/app/resume'
    | '/app/skill-gaps'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/app'
    | '/api/coach'
    | '/app/coach'
    | '/app/github'
    | '/app/job-match'
    | '/app/plan'
    | '/app/portfolio'
    | '/app/resume'
    | '/app/skill-gaps'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  AppRoute: typeof AppRouteWithChildren
  ApiCoachRoute: typeof ApiCoachRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coach': {
      id: '/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/github': {
      id: '/app/github'
      path: '/github'
      fullPath: '/app/github'
      preLoaderRoute: typeof AppGithubRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/job-match': {
      id: '/app/job-match'
      path: '/job-match'
      fullPath: '/app/job-match'
      preLoaderRoute: typeof AppJobMatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plan': {
      id: '/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portfolio': {
      id: '/app/portfolio'
      path: '/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resume': {
      id: '/app/resume'
      path: '/resume'
      fullPath: '/app/resume'
      preLoaderRoute: typeof AppResumeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/skill-gaps': {
      id: '/app/skill-gaps'
      path: '/skill-gaps'
      fullPath: '/app/skill-gaps'
      preLoaderRoute: typeof AppSkillGapsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCoachRoute: typeof AppCoachRoute
  AppGithubRoute: typeof AppGithubRoute
  AppJobMatchRoute: typeof AppJobMatchRoute
  AppPlanRoute: typeof AppPlanRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppResumeRoute: typeof AppResumeRoute
  AppSkillGapsRoute: typeof AppSkillGapsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoachRoute: AppCoachRoute,
  AppGithubRoute: AppGithubRoute,
  AppJobMatchRoute: AppJobMatchRoute,
  AppPlanRoute: AppPlanRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppResumeRoute: AppResumeRoute,
  AppSkillGapsRoute: AppSkillGapsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  AppRoute: AppRouteWithChildren,
  ApiCoachRoute: ApiCoachRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
